apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodev-worker
  namespace: crewai-workers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: autodev-worker
  template:
    metadata:
      labels:
        app: autodev-worker
    spec:
      serviceAccountName: crewai-worker-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: worker
        image: autodev/worker:latest
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: autodev-secrets
              key: redis-url
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}

## Service account for the worker
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crewai-worker-sa
  namespace: crewai-workers
