apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-lifecycle-config
data:
  lifecycle.json: |
    {
      "Rules": [
        {
          "ID": "CrewAI-Artifacts-Lifecycle",
          "Status": "Enabled",
          "Filter": {"Prefix": "artifacts/"},
          "Transitions": [
            {"Days": 30, "StorageClass": "STANDARD_IA"},
            {"Days": 90, "StorageClass": "GLACIER"},
            {"Days": 365, "StorageClass": "DEEP_ARCHIVE"}
          ],
          "NoncurrentVersionTransitions": [
            {"NoncurrentDays": 7, "StorageClass": "STANDARD_IA"},
            {"NoncurrentDays": 30, "StorageClass": "GLACIER"}
          ],
          "NoncurrentVersionExpiration": {"NoncurrentDays": 730}
        },
        {
          "ID": "Execution-Logs-Cleanup",
          "Status": "Enabled",
          "Filter": {"Prefix": "logs/"},
          "Expiration": {"Days": 90}
        }
      ]
    }
